import {
  FaJava,
  FaNodeJs,
  FaAws,
  FaGitAlt,
  FaDocker,
  FaPython,
  FaTools,
  FaTasks,
  FaProjectDiagram,
  FaCloud
} from "react-icons/fa";
import { AiOutlineRobot, AiOutlineApi } from "react-icons/ai";
import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiRedux,
  SiAngular,
  SiHtml5,
  SiCss3,
  SiSpring,
  SiSpringboot,
  SiHibernate,
  SiMysql,
  SiMongodb,
  SiPostgresql,
  SiKubernetes,
  SiJenkins,
  SiGithub,
  SiVisualstudiocode,
  SiIntellijidea,
  SiEclipseide,
  SiWebpack,
  SiApachekafka,
  SiMariadbfoundation,
  SiRabbitmq,
  SiSplunk,
  SiJest,
  SiCucumber,
  SiThealgorithms,
  SiSwagger,
  SiTensorflow
} from "react-icons/si";
import { BsBootstrap } from "react-icons/bs";

export const TechStackList = [
  { _id: 46, name: "SpringCloud", icon: FaCloud },
  { _id: 45, name: "SpringAI", icon: SiSpring },
  { _id: 47, name: "MachineLearning", icon: SiTensorflow },
  { _id: 42, name: "Data Structures", icon: FaProjectDiagram },
  { _id: 1, name: "Java", icon: FaJava },
  { _id: 2, name: "JavaScript", icon: SiJavascript },
  { _id: 3, name: "TypeScript", icon: SiTypescript },
  { _id: 4, name: "Python", icon: FaPython },
  { _id: 5, name: "ReactJs", icon: SiReact },
  { _id: 6, name: "Redux", icon: SiRedux },
  { _id: 7, name: "Angular", icon: SiAngular },
  { _id: 8, name: "HTML", icon: SiHtml5 },
  { _id: 9, name: "CSS", icon: SiCss3 },
  { _id: 10, name: "JavaScript", icon: SiJavascript },
  { _id: 11, name: "NodeJs", icon: FaNodeJs },
  { _id: 12, name: "Express", icon: FaNodeJs },
  { _id: 13, name: "Spring", icon: SiSpring },
  { _id: 14, name: "Spring Boot", icon: SiSpringboot },
  { _id: 15, name: "Hibernate", icon: SiHibernate },
  { _id: 16, name: "RESTful APIs", icon: AiOutlineApi },
  { _id: 17, name: "Microservices", icon: SiSpringboot },
  { _id: 18, name: "MySQL", icon: SiMysql },
  { _id: 19, name: "MongoDB", icon: SiMongodb },
  { _id: 20, name: "PostgreSQL", icon: SiPostgresql },
  { _id: 21, name: "AWS", icon: FaAws },
  { _id: 22, name: "Docker", icon: FaDocker },
  { _id: 23, name: "Kubernetes", icon: SiKubernetes },
  { _id: 24, name: "Jenkins", icon: SiJenkins },
  { _id: 25, name: "GitHub", icon: SiGithub },
  { _id: 26, name: "Git", icon: FaGitAlt },
  { _id: 27, name: "IntelliJ IDEA", icon: SiIntellijidea },
  { _id: 28, name: "VS Code", icon: SiVisualstudiocode },
  { _id: 29, name: "Eclipse", icon: SiEclipseide },
  { _id: 30, name: "Webpack", icon: SiWebpack },
  { _id: 31, name: "Apache Kafka", icon: SiApachekafka },
  { _id: 32, name: "MariaDB", icon: SiMariadbfoundation },
  { _id: 33, name: "Selenium", icon: AiOutlineRobot },
  { _id: 34, name: "Cucumber", icon: SiCucumber },
  { _id: 35, name: "Splunk", icon: SiSplunk },
  { _id: 36, name: "RabbitMQ", icon: SiRabbitmq },
  { _id: 37, name: "Postman", icon: FaTools },
  { _id: 38, name: "Jest", icon: SiJest },
  { _id: 39, name: "Algorithem", icon: SiThealgorithms },
  { _id: 40, name: "JUnit", icon: FaJava },
  { _id: 41, name: "Agile Methodology", icon: FaTasks },
  { _id: 43, name: "Bootstrap", icon: BsBootstrap },
  { _id: 44, name: "Swagger", icon: SiSwagger }
];
